LOW_BALANCE_THRESHOLD = 250

ARTIFACT_TTL_HOURS = 72

TRUST_MAX_DISCOUNT = 0.10

DAILY_PREMIUM_ESCALATION_AFTER = 2
DAILY_PREMIUM_ESCALATION_MULTIPLIER = 1.2

MAX_UPGRADES_PER_OBJECT = 2

PRICING = {
    "UNLOCK_IMAGE": 50,
    "UNLOCK_VIDEO": 200,
    "UPGRADE_IMAGE": 30,
    "UPGRADE_VIDEO": 100,
}
